# -*- coding: utf-8 -*-
"""UR3e_jacobian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DShqRJNUjA9whPGGhyHFZSwUdtffi83U
"""

import sympy as sp

# Data for question 2
th1, th2, th3, th4, th5, th6 = sp.symbols('th1 th2 th3 th4 th5 th6') #symbols used (has to be changed accordingly)
a = sp.Matrix([0, 0, 0.14500])  # coordinate of end effector in nth link frame (has to be changed accordingly)
epsilon = [1, 1, 1, 1, 1, 1] # has to be changed accordingly
dh = sp.Matrix([
    [(sp.pi)/2, 0, 0.15185, th1],
    [0, -0.24355, 0, th2],
    [0, -0.2132, 0, th3],
    [(sp.pi)/2, 0, 0.13105, th4],
    [-(sp.pi)/2, 0, 0.08535, th5],
    [0, 0, 0.0921, th6]
])

n_links = dh.shape[0]  # number of links

# Finding homogeneous transformation matrix
T = sp.eye(4)
for n in range(n_links):
    t = sp.Matrix([
        [sp.cos(dh[n, 3]), -sp.sin(dh[n, 3]) * sp.cos(dh[n, 0]), sp.sin(dh[n, 3]) * sp.sin(dh[n, 0]), dh[n, 1] * sp.cos(dh[n, 3])],
        [sp.sin(dh[n, 3]), sp.cos(dh[n, 3]) * sp.cos(dh[n, 0]), -sp.cos(dh[n, 3]) * sp.sin(dh[n, 0]), dh[n, 1] * sp.sin(dh[n, 3])],
        [0, sp.sin(dh[n, 0]), sp.cos(dh[n, 0]), dh[n, 2]],
        [0, 0, 0, 1]
    ])
    T = T * t

R = T[:3, :3]  # Rotation matrix
O = T[:3, 3]   # Translation matrix
p = T * sp.Matrix([*a, 1])
P = p[:3, 0]  # Position matrix of end effector wrt base

# Displaying matrices
print('The homogenous transformation matrix is as follows:')
sp.pprint(T)
print('The rotation matrix is as follows:')
sp.pprint(R)
print('The translation matrix is as follows:')
sp.pprint(O)
print('The position matrix of end effector wrt to base is as follows:')
sp.pprint(P)

import numpy as np

# Finding Jacobian matrix
T1 = sp.eye(4)
Jv = sp.zeros(3, n_links)
Jw = sp.zeros(3, n_links)

for n in range(n_links):
    t = sp.Matrix([
        [sp.cos(dh[n, 3]), -sp.sin(dh[n, 3]) * sp.cos(dh[n, 0]), sp.sin(dh[n, 3]) * sp.sin(dh[n, 0]), dh[n, 1] * sp.cos(dh[n, 3])],
        [sp.sin(dh[n, 3]), sp.cos(dh[n, 3]) * sp.cos(dh[n, 0]), -sp.cos(dh[n, 3]) * sp.sin(dh[n, 0]), dh[n, 1] * sp.sin(dh[n, 3])],
        [0, sp.sin(dh[n, 0]), sp.cos(dh[n, 0]), dh[n, 2]],
        [0, 0, 0, 1]
    ])
    T1 = T1 * t

    Z = T1[:3, 2]
    oo = T1[:3, 3]
    Jv[:, n] = epsilon[n] * Z.cross(P - oo) + (1 - epsilon[n]) * Z
    Jw[:, n] = epsilon[n] * Z

J = Jv.col_join(Jw)  # Jacobian matrix

print('The jacobian matrix is as follows:')
sp.pprint(J)

# Singular values

if J.shape[0] == J.shape[1]:
    #J_inv = J.inv()
    determinant = J.det()
    print('The singular configuration is as follows:')
    sp.pprint(determinant)
    #print('The inverse of the Jacobian matrix is as follows:')
    #sp.pprint(J_inv)
else:
    print('The Jacobian matrix is not square, so its inverse cannot be computed.')